name: Docker Image CI - Tools

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch: # Agrega esta entrada para habilitar la ejecución manual
    branches: [ "master", "main" ] # Opcional: restringe las ramas donde se puede ejecutar

jobs:

  build_push_image_tools:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Download codigo from repo
      
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}
        
    
    - name: Build and push the Docker image latest
      run: |
        docker build . --file Dockerfile --tag neytor/tools && 
        docker image ls && docker push neytor/tools
      
    

